id: rack-services
name: Services Rack
u_height: 42
template_id: rack-42u-air
devices:
- id: login-01
  name: login01
  template_id: generic-1u-login
  u_position: 1
  face: front
  instance: login01
- id: login-02
  name: login02
  template_id: generic-1u-login
  u_position: 2
  face: front
  instance: login02
- id: login-03
  name: login03
  template_id: generic-1u-login
  u_position: 3
  face: front
  instance: login03
- id: login-04
  name: login04
  template_id: generic-1u-login
  u_position: 4
  face: front
  instance: login04
- id: login-05
  name: login05
  template_id: generic-1u-login
  u_position: 5
  face: front
  instance: login05
- id: login-06
  name: login06
  template_id: generic-1u-login
  u_position: 6
  face: front
  instance: login06
- id: visu-01
  name: visu01
  template_id: generic-2u-visu
  u_position: 7
  face: front
  instance:
    1: visu001
- id: visu-02
  name: visu02
  template_id: generic-2u-visu
  u_position: 9
  face: front
  instance:
    1: visu002
- id: visu-03
  name: visu03
  template_id: generic-2u-visu
  u_position: 11
  face: front
  instance:
    1: visu003
- id: visu-04
  name: visu04
  template_id: generic-2u-visu
  u_position: 13
  face: front
  instance:
    1: visu004
- id: visu-05
  name: visu05
  template_id: generic-2u-visu
  u_position: 15
  face: front
  instance:
    1: visu005
- id: visu-06
  name: visu06
  template_id: generic-2u-visu
  u_position: 17
  face: front
  instance:
    1: visu006
- id: mgmt-01
  name: mgmt01
  template_id: generic-1u-mgmt
  u_position: 19
  face: front
  instance: mgmt01
- id: mgmt-02
  name: mgmt02
  template_id: generic-1u-mgmt
  u_position: 20
  face: front
  instance: mgmt02
- id: mgmt-03
  name: mgmt03
  template_id: generic-1u-mgmt
  u_position: 21
  face: front
  instance: mgmt03
- id: mgmt-04
  name: mgmt04
  template_id: generic-1u-mgmt
  u_position: 22
  face: front
  instance: mgmt04
- id: mgmt-05
  name: mgmt05
  template_id: generic-1u-mgmt
  u_position: 23
  face: front
  instance: mgmt05
- id: mon-01
  name: monitoring01
  template_id: generic-1u-mgmt
  u_position: 24
  face: front
  instance: monitoring01
- id: mon-02
  name: monitoring02
  template_id: generic-1u-mgmt
  u_position: 25
  face: front
  instance: monitoring02
- id: mon-03
  name: monitoring03
  template_id: generic-1u-mgmt
  u_position: 26
  face: front
  instance: monitoring03
- id: sw-eth-rack-services
  name: tor-rack-services
  template_id: generic-tor-eth-1u
  u_position: 42
  face: front
  instance: tor-rack-services
- id: sw-ib-rack-services
  name: ib-rack-services
  template_id: generic-ib-switch-1u
  u_position: 41
  face: front
  instance: ib-rack-services
