id: r01-05
name: Rack XH3000 Compute 05
template_id: bull-xh3000
aisle_id: aisle-01
u_height: 42
devices:
- id: r01-05-ib
  name: IB Switch XH35MQ
  template_id: bs-xh35mq-ib-1u
  u_position: 12
- id: r01-05-c01
  name: XH3420 Mato 01
  template_id: bs-xh3420-mato-1u-3n
  u_position: 1
  nodes: compute[111-113]
- id: r01-05-c02
  name: XH3420 Mato 02
  template_id: bs-xh3420-mato-1u-3n
  u_position: 2
  nodes: compute[114-116]
- id: r01-05-c03
  name: XH3420 Mato 03
  template_id: bs-xh3420-mato-1u-3n
  u_position: 3
  nodes: compute[117-119]
- id: r01-05-c04
  name: XH3420 Mato 04
  template_id: bs-xh3420-mato-1u-3n
  u_position: 4
  nodes: compute[120-122]
- id: r01-05-c05
  name: XH3420 Mato 05
  template_id: bs-xh3420-mato-1u-3n
  u_position: 5
  nodes: compute[123-125]
- id: r01-05-c06
  name: XH3420 Mato 06
  template_id: bs-xh3420-mato-1u-3n
  u_position: 6
  nodes: compute[126-128]
- id: r01-05-c07
  name: XH3420 Mato 07
  template_id: bs-xh3420-mato-1u-3n
  u_position: 7
  nodes: compute[129-131]
- id: r01-05-c08
  name: XH3420 Mato 08
  template_id: bs-xh3420-mato-1u-3n
  u_position: 8
  nodes: compute[132-134]
- id: r01-05-c09
  name: XH3420 Mato 09
  template_id: bs-xh3420-mato-1u-3n
  u_position: 9
  nodes: compute[135-137]
- id: r01-05-c10
  name: XH3420 Mato 10
  template_id: bs-xh3420-mato-1u-3n
  u_position: 10
  nodes: compute[138-140]
