id: aisle-compute-5
name: Aisle Compute 5
room_id: room-compute-b
racks:
- id: rack-par-c013
- id: rack-par-c014
- id: rack-par-c015
- id: rack-par-c016
- id: rack-par-c017
- id: rack-par-c018
- id: rack-par-c019
- id: rack-par-c020
- id: rack-par-c021
- id: rack-par-c022
