templates:
- id: bs-2u-twin-visu
  name: BullSequana Visu Node (2U)
  type: server
  u_height: 2
  layout:
    type: grid
    rows: 1
    cols: 2
    matrix:
    - - 1
      - 2
  rear_layout:
    type: grid
    rows: 1
    cols: 2
    matrix:
    - - 901
      - 902
