templates:
- id: bs-4u-quad-gpu
  name: BullSequana X2415 (4U Quad GPU)
  type: server
  u_height: 4
  layout:
    type: grid
    rows: 2
    cols: 2
    matrix:
    - - 1
      - 2
    - - 3
      - 4
  rear_layout:
    type: grid
    rows: 1
    cols: 4
    matrix:
    - - 901
      - 902
      - 903
      - 904
