templates:
- id: bs-x430-service-2u
  name: BullSequana X430 Service (2U 1 Node)
  type: server
  u_height: 2
  layout:
    type: grid
    rows: 1
    cols: 1
    matrix:
      - [1]
  rear_layout:
    type: grid
    rows: 1
    cols: 2
    matrix:
      - [901, 902]
  rear_components:
  - id: '901'
    name: Rear Fan
    type: fan
    checks:
    - ipmi_fan_speed_state
    - ipmi_sensor_state
  - id: '902'
    name: Rear PSU
    type: psu
    checks:
    - ipmi_power_state
    - ipmi_voltage_state
  checks:
  - node_up
  - node_recent_reboot
  - ipmi_up
  - ipmi_fan_speed_state
  - ipmi_power_state
  - ipmi_sensor_state
  - ipmi_temperature_state
  - ipmi_voltage_state
