templates:
  - id: bs-xh3515-neba-1u-2n
    name: BullSequana XH3515 Neba (1U 2 Nodes)
    type: server
    u_height: 1
    layout:
      type: grid
      rows: 1
      cols: 2
      matrix:
        - [1, 2]
