templates:
  - id: bs-xh3420-mato-1u-3n
    name: BullSequana XH3420 Mato (1U 3 Nodes)
    type: server
    u_height: 1
    layout:
      type: grid
      rows: 1
      cols: 3
      matrix:
        - [1, 2, 3]
