id: rack-c09
name: Compute Rack C09
u_height: 42
template_id: rack-42u-dcw
devices:
- id: cc09-01
  name: compute0961-compute0963
  template_id: hpc-1u-3node
  u_position: 1
  face: front
  instance:
    1: compute0961
    2: compute0962
    3: compute0963
- id: cc09-02
  name: compute0964-compute0966
  template_id: hpc-1u-3node
  u_position: 2
  face: front
  instance:
    1: compute0964
    2: compute0965
    3: compute0966
- id: cc09-03
  name: compute0967-compute0969
  template_id: hpc-1u-3node
  u_position: 3
  face: front
  instance:
    1: compute0967
    2: compute0968
    3: compute0969
- id: cc09-04
  name: compute0970-compute0972
  template_id: hpc-1u-3node
  u_position: 4
  face: front
  instance:
    1: compute0970
    2: compute0971
    3: compute0972
- id: cc09-05
  name: compute0973-compute0975
  template_id: hpc-1u-3node
  u_position: 5
  face: front
  instance:
    1: compute0973
    2: compute0974
    3: compute0975
- id: cc09-06
  name: compute0976-compute0978
  template_id: hpc-1u-3node
  u_position: 6
  face: front
  instance:
    1: compute0976
    2: compute0977
    3: compute0978
- id: cc09-07
  name: compute0979-compute0981
  template_id: hpc-1u-3node
  u_position: 7
  face: front
  instance:
    1: compute0979
    2: compute0980
    3: compute0981
- id: cc09-08
  name: compute0982-compute0984
  template_id: hpc-1u-3node
  u_position: 8
  face: front
  instance:
    1: compute0982
    2: compute0983
    3: compute0984
- id: cc09-09
  name: compute0985-compute0987
  template_id: hpc-1u-3node
  u_position: 9
  face: front
  instance:
    1: compute0985
    2: compute0986
    3: compute0987
- id: cc09-10
  name: compute0988-compute0990
  template_id: hpc-1u-3node
  u_position: 10
  face: front
  instance:
    1: compute0988
    2: compute0989
    3: compute0990
- id: cc09-11
  name: compute0991-compute0993
  template_id: hpc-1u-3node
  u_position: 11
  face: front
  instance:
    1: compute0991
    2: compute0992
    3: compute0993
- id: cc09-12
  name: compute0994-compute0996
  template_id: hpc-1u-3node
  u_position: 12
  face: front
  instance:
    1: compute0994
    2: compute0995
    3: compute0996
- id: cc09-13
  name: compute0997-compute0999
  template_id: hpc-1u-3node
  u_position: 13
  face: front
  instance:
    1: compute0997
    2: compute0998
    3: compute0999
- id: cc09-14
  name: compute1000-compute1002
  template_id: hpc-1u-3node
  u_position: 14
  face: front
  instance:
    1: compute1000
    2: compute1001
    3: compute1002
- id: cc09-15
  name: compute1003-compute1005
  template_id: hpc-1u-3node
  u_position: 15
  face: front
  instance:
    1: compute1003
    2: compute1004
    3: compute1005
- id: cc09-16
  name: compute1006-compute1008
  template_id: hpc-1u-3node
  u_position: 16
  face: front
  instance:
    1: compute1006
    2: compute1007
    3: compute1008
- id: cc09-17
  name: compute1009-compute1011
  template_id: hpc-1u-3node
  u_position: 17
  face: front
  instance:
    1: compute1009
    2: compute1010
    3: compute1011
- id: cc09-18
  name: compute1012-compute1014
  template_id: hpc-1u-3node
  u_position: 18
  face: front
  instance:
    1: compute1012
    2: compute1013
    3: compute1014
- id: cc09-19
  name: compute1015-compute1017
  template_id: hpc-1u-3node
  u_position: 19
  face: front
  instance:
    1: compute1015
    2: compute1016
    3: compute1017
- id: cc09-20
  name: compute1018-compute1020
  template_id: hpc-1u-3node
  u_position: 20
  face: front
  instance:
    1: compute1018
    2: compute1019
    3: compute1020
- id: cc09-21
  name: compute1021-compute1023
  template_id: hpc-1u-3node
  u_position: 21
  face: front
  instance:
    1: compute1021
    2: compute1022
    3: compute1023
- id: cc09-22
  name: compute1024-compute1026
  template_id: hpc-1u-3node
  u_position: 22
  face: front
  instance:
    1: compute1024
    2: compute1025
    3: compute1026
- id: cc09-23
  name: compute1027-compute1029
  template_id: hpc-1u-3node
  u_position: 23
  face: front
  instance:
    1: compute1027
    2: compute1028
    3: compute1029
- id: cc09-24
  name: compute1030-compute1032
  template_id: hpc-1u-3node
  u_position: 24
  face: front
  instance:
    1: compute1030
    2: compute1031
    3: compute1032
- id: cc09-25
  name: compute1033-compute1035
  template_id: hpc-1u-3node
  u_position: 25
  face: front
  instance:
    1: compute1033
    2: compute1034
    3: compute1035
- id: cc09-26
  name: compute1036-compute1038
  template_id: hpc-1u-3node
  u_position: 26
  face: front
  instance:
    1: compute1036
    2: compute1037
    3: compute1038
- id: cc09-27
  name: compute1039-compute1041
  template_id: hpc-1u-3node
  u_position: 27
  face: front
  instance:
    1: compute1039
    2: compute1040
    3: compute1041
- id: cc09-28
  name: compute1042-compute1044
  template_id: hpc-1u-3node
  u_position: 28
  face: front
  instance:
    1: compute1042
    2: compute1043
    3: compute1044
- id: cc09-29
  name: compute1045-compute1047
  template_id: hpc-1u-3node
  u_position: 29
  face: front
  instance:
    1: compute1045
    2: compute1046
    3: compute1047
- id: cc09-30
  name: compute1048-compute1050
  template_id: hpc-1u-3node
  u_position: 30
  face: front
  instance:
    1: compute1048
    2: compute1049
    3: compute1050
- id: cc09-31
  name: compute1051-compute1053
  template_id: hpc-1u-3node
  u_position: 31
  face: front
  instance:
    1: compute1051
    2: compute1052
    3: compute1053
- id: cc09-32
  name: compute1054-compute1056
  template_id: hpc-1u-3node
  u_position: 32
  face: front
  instance:
    1: compute1054
    2: compute1055
    3: compute1056
- id: cc09-33
  name: compute1057-compute1059
  template_id: hpc-1u-3node
  u_position: 33
  face: front
  instance:
    1: compute1057
    2: compute1058
    3: compute1059
- id: cc09-34
  name: compute1060-compute1062
  template_id: hpc-1u-3node
  u_position: 34
  face: front
  instance:
    1: compute1060
    2: compute1061
    3: compute1062
- id: cc09-35
  name: compute1063-compute1065
  template_id: hpc-1u-3node
  u_position: 35
  face: front
  instance:
    1: compute1063
    2: compute1064
    3: compute1065
- id: cc09-36
  name: compute1066-compute1068
  template_id: hpc-1u-3node
  u_position: 36
  face: front
  instance:
    1: compute1066
    2: compute1067
    3: compute1068
- id: cc09-37
  name: compute1069-compute1071
  template_id: hpc-1u-3node
  u_position: 37
  face: front
  instance:
    1: compute1069
    2: compute1070
    3: compute1071
- id: cc09-38
  name: compute1072-compute1074
  template_id: hpc-1u-3node
  u_position: 38
  face: front
  instance:
    1: compute1072
    2: compute1073
    3: compute1074
- id: cc09-39
  name: compute1075-compute1077
  template_id: hpc-1u-3node
  u_position: 39
  face: front
  instance:
    1: compute1075
    2: compute1076
    3: compute1077
- id: cc09-40
  name: compute1078-compute1080
  template_id: hpc-1u-3node
  u_position: 40
  face: front
  instance:
    1: compute1078
    2: compute1079
    3: compute1080
- id: tor-rack-c09
  name: tor-rack-c09
  template_id: generic-tor-eth-1u
  u_position: 42
  face: front
  instance: tor-rack-c09
