id: rack-tls-hm02
name: High-Memory Rack TLS HM02
u_height: 42
template_id: bull-xh3000
devices:
- id: hpc-tls-hm02-01
  name: tls-hm077-tls-hm078
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 1
  face: front
  instance:
    1: tls-hm077
    2: tls-hm078
- id: hpc-tls-hm02-02
  name: tls-hm079-tls-hm080
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 2
  face: front
  instance:
    1: tls-hm079
    2: tls-hm080
- id: hpc-tls-hm02-03
  name: tls-hm081-tls-hm082
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 3
  face: front
  instance:
    1: tls-hm081
    2: tls-hm082
- id: hpc-tls-hm02-04
  name: tls-hm083-tls-hm084
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 4
  face: front
  instance:
    1: tls-hm083
    2: tls-hm084
- id: hpc-tls-hm02-05
  name: tls-hm085-tls-hm086
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 5
  face: front
  instance:
    1: tls-hm085
    2: tls-hm086
- id: hpc-tls-hm02-06
  name: tls-hm087-tls-hm088
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 6
  face: front
  instance:
    1: tls-hm087
    2: tls-hm088
- id: hpc-tls-hm02-07
  name: tls-hm089-tls-hm090
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 7
  face: front
  instance:
    1: tls-hm089
    2: tls-hm090
- id: hpc-tls-hm02-08
  name: tls-hm091-tls-hm092
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 8
  face: front
  instance:
    1: tls-hm091
    2: tls-hm092
- id: hpc-tls-hm02-09
  name: tls-hm093-tls-hm094
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 9
  face: front
  instance:
    1: tls-hm093
    2: tls-hm094
- id: hpc-tls-hm02-10
  name: tls-hm095-tls-hm096
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 10
  face: front
  instance:
    1: tls-hm095
    2: tls-hm096
- id: hpc-tls-hm02-11
  name: tls-hm097-tls-hm098
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 11
  face: front
  instance:
    1: tls-hm097
    2: tls-hm098
- id: hpc-tls-hm02-12
  name: tls-hm099-tls-hm100
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 12
  face: front
  instance:
    1: tls-hm099
    2: tls-hm100
- id: hpc-tls-hm02-13
  name: tls-hm101-tls-hm102
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 13
  face: front
  instance:
    1: tls-hm101
    2: tls-hm102
- id: hpc-tls-hm02-14
  name: tls-hm103-tls-hm104
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 14
  face: front
  instance:
    1: tls-hm103
    2: tls-hm104
- id: hpc-tls-hm02-15
  name: tls-hm105-tls-hm106
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 15
  face: front
  instance:
    1: tls-hm105
    2: tls-hm106
- id: hpc-tls-hm02-16
  name: tls-hm107-tls-hm108
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 16
  face: front
  instance:
    1: tls-hm107
    2: tls-hm108
- id: hpc-tls-hm02-17
  name: tls-hm109-tls-hm110
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 17
  face: front
  instance:
    1: tls-hm109
    2: tls-hm110
- id: hpc-tls-hm02-18
  name: tls-hm111-tls-hm112
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 18
  face: front
  instance:
    1: tls-hm111
    2: tls-hm112
- id: hpc-tls-hm02-19
  name: tls-hm113-tls-hm114
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 19
  face: front
  instance:
    1: tls-hm113
    2: tls-hm114
- id: hpc-tls-hm02-20
  name: tls-hm115-tls-hm116
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 20
  face: front
  instance:
    1: tls-hm115
    2: tls-hm116
- id: hpc-tls-hm02-21
  name: tls-hm117-tls-hm118
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 21
  face: front
  instance:
    1: tls-hm117
    2: tls-hm118
- id: hpc-tls-hm02-22
  name: tls-hm119-tls-hm120
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 22
  face: front
  instance:
    1: tls-hm119
    2: tls-hm120
- id: hpc-tls-hm02-23
  name: tls-hm121-tls-hm122
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 23
  face: front
  instance:
    1: tls-hm121
    2: tls-hm122
- id: hpc-tls-hm02-24
  name: tls-hm123-tls-hm124
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 24
  face: front
  instance:
    1: tls-hm123
    2: tls-hm124
- id: hpc-tls-hm02-25
  name: tls-hm125-tls-hm126
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 25
  face: front
  instance:
    1: tls-hm125
    2: tls-hm126
- id: hpc-tls-hm02-26
  name: tls-hm127-tls-hm128
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 26
  face: front
  instance:
    1: tls-hm127
    2: tls-hm128
- id: hpc-tls-hm02-27
  name: tls-hm129-tls-hm130
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 27
  face: front
  instance:
    1: tls-hm129
    2: tls-hm130
- id: hpc-tls-hm02-28
  name: tls-hm131-tls-hm132
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 28
  face: front
  instance:
    1: tls-hm131
    2: tls-hm132
- id: hpc-tls-hm02-29
  name: tls-hm133-tls-hm134
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 29
  face: front
  instance:
    1: tls-hm133
    2: tls-hm134
- id: hpc-tls-hm02-30
  name: tls-hm135-tls-hm136
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 30
  face: front
  instance:
    1: tls-hm135
    2: tls-hm136
- id: hpc-tls-hm02-31
  name: tls-hm137-tls-hm138
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 31
  face: front
  instance:
    1: tls-hm137
    2: tls-hm138
- id: hpc-tls-hm02-32
  name: tls-hm139-tls-hm140
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 32
  face: front
  instance:
    1: tls-hm139
    2: tls-hm140
- id: hpc-tls-hm02-33
  name: tls-hm141-tls-hm142
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 33
  face: front
  instance:
    1: tls-hm141
    2: tls-hm142
- id: hpc-tls-hm02-34
  name: tls-hm143-tls-hm144
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 34
  face: front
  instance:
    1: tls-hm143
    2: tls-hm144
- id: hpc-tls-hm02-35
  name: tls-hm145-tls-hm146
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 35
  face: front
  instance:
    1: tls-hm145
    2: tls-hm146
- id: hpc-tls-hm02-36
  name: tls-hm147-tls-hm148
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 36
  face: front
  instance:
    1: tls-hm147
    2: tls-hm148
- id: hpc-tls-hm02-37
  name: tls-hm149-tls-hm150
  template_id: bs-xh3145-tiya-1u-2n
  u_position: 37
  face: front
  instance:
    1: tls-hm149
    2: tls-hm150
- id: sw-ib-tls-hm02
  name: sw-ib-tls-hm02
  template_id: bs-xh35mq-ib-1u
  u_position: 38
  face: front
  instance: sw-ib-tls-hm02
