rack_templates:
  - id: bull-xh3000
    name: BullSequana XH3000 DLC
    u_height: 42
    infrastructure:
      front_components:
        - id: p3sm
          name: P3SM [1,2]
          type: power
          model: P3SM
          location: u-mount
          u_position: 39
          u_height: 3
        - id: pmc
          name: PMC
          type: power
          model: PMC
          location: u-mount
          u_position: 42
          u_height: 1
      rear_components:
        - id: h3e
          name: H3E
          type: cooling
          model: H3E
          location: u-mount
          u_position: 1
          u_height: 11
        - id: h3p0
          name: H3P0
          type: cooling
          model: H3P0
          location: u-mount
          u_position: 12
          u_height: 10
        - id: h3p1
          name: H3P1
          type: cooling
          model: H3P1
          location: u-mount
          u_position: 22
          u_height: 10
        - id: w3am2
          name: W3AM2
          type: management
          model: W3AM2
          location: u-mount
          u_position: 32
          u_height: 1
        - id: w3am1
          name: W3AM1
          type: management
          model: W3AM1
          location: u-mount
          u_position: 33
          u_height: 1
        - id: w3am0
          name: W3AM0
          type: management
          model: W3AM0
          location: u-mount
          u_position: 34
          u_height: 1
