id: rack-c01
name: Compute Rack C01
u_height: 42
template_id: rack-42u-air
devices:
- id: cc01-01
  name: compute001-compute004
  template_id: generic-2u-quad
  u_position: 1
  face: front
  instance:
    1: compute001
    2: compute002
    3: compute003
    4: compute004
- id: cc01-03
  name: compute005-compute008
  template_id: generic-2u-quad
  u_position: 3
  face: front
  instance:
    1: compute005
    2: compute006
    3: compute007
    4: compute008
- id: cc01-05
  name: compute009-compute012
  template_id: generic-2u-quad
  u_position: 5
  face: front
  instance:
    1: compute009
    2: compute010
    3: compute011
    4: compute012
- id: cc01-07
  name: compute013-compute016
  template_id: generic-2u-quad
  u_position: 7
  face: front
  instance:
    1: compute013
    2: compute014
    3: compute015
    4: compute016
- id: cc01-09
  name: compute017-compute020
  template_id: generic-2u-quad
  u_position: 9
  face: front
  instance:
    1: compute017
    2: compute018
    3: compute019
    4: compute020
- id: cc01-11
  name: compute021-compute024
  template_id: generic-2u-quad
  u_position: 11
  face: front
  instance:
    1: compute021
    2: compute022
    3: compute023
    4: compute024
- id: cc01-13
  name: compute025-compute028
  template_id: generic-2u-quad
  u_position: 13
  face: front
  instance:
    1: compute025
    2: compute026
    3: compute027
    4: compute028
- id: cc01-15
  name: compute029-compute032
  template_id: generic-2u-quad
  u_position: 15
  face: front
  instance:
    1: compute029
    2: compute030
    3: compute031
    4: compute032
- id: cc01-17
  name: compute033-compute036
  template_id: generic-2u-quad
  u_position: 17
  face: front
  instance:
    1: compute033
    2: compute034
    3: compute035
    4: compute036
- id: cc01-19
  name: compute037-compute040
  template_id: generic-2u-quad
  u_position: 19
  face: front
  instance:
    1: compute037
    2: compute038
    3: compute039
    4: compute040
- id: cc01-21
  name: compute041-compute044
  template_id: generic-2u-quad
  u_position: 21
  face: front
  instance:
    1: compute041
    2: compute042
    3: compute043
    4: compute044
- id: cc01-23
  name: compute045-compute048
  template_id: generic-2u-quad
  u_position: 23
  face: front
  instance:
    1: compute045
    2: compute046
    3: compute047
    4: compute048
- id: cc01-25
  name: compute049-compute052
  template_id: generic-2u-quad
  u_position: 25
  face: front
  instance:
    1: compute049
    2: compute050
    3: compute051
    4: compute052
- id: cc01-27
  name: compute053-compute056
  template_id: generic-2u-quad
  u_position: 27
  face: front
  instance:
    1: compute053
    2: compute054
    3: compute055
    4: compute056
- id: cc01-29
  name: compute057-compute060
  template_id: generic-2u-quad
  u_position: 29
  face: front
  instance:
    1: compute057
    2: compute058
    3: compute059
    4: compute060
- id: cc01-31
  name: compute061-compute064
  template_id: generic-2u-quad
  u_position: 31
  face: front
  instance:
    1: compute061
    2: compute062
    3: compute063
    4: compute064
- id: cc01-33
  name: compute065-compute068
  template_id: generic-2u-quad
  u_position: 33
  face: front
  instance:
    1: compute065
    2: compute066
    3: compute067
    4: compute068
- id: cc01-35
  name: compute069-compute072
  template_id: generic-2u-quad
  u_position: 35
  face: front
  instance:
    1: compute069
    2: compute070
    3: compute071
    4: compute072
- id: cc01-37
  name: compute073-compute076
  template_id: generic-2u-quad
  u_position: 37
  face: front
  instance:
    1: compute073
    2: compute074
    3: compute075
    4: compute076
- id: cc01-39
  name: compute077-compute080
  template_id: generic-2u-quad
  u_position: 39
  face: front
  instance:
    1: compute077
    2: compute078
    3: compute079
    4: compute080
- id: tor-rack-c01
  name: tor-rack-c01
  template_id: generic-tor-eth-1u
  u_position: 42
  face: front
  instance: tor-rack-c01
