id: rack-gpu01
name: GPU Rack GPU01
u_height: 42
template_id: rack-42u-dcw
devices:
- id: ggpu01-01
  name: gpu001-gpu004
  template_id: hpc-4u-quad-gpu
  u_position: 1
  face: front
  instance:
    1: gpu001
    2: gpu002
    3: gpu003
    4: gpu004
- id: ggpu01-05
  name: gpu005-gpu008
  template_id: hpc-4u-quad-gpu
  u_position: 5
  face: front
  instance:
    1: gpu005
    2: gpu006
    3: gpu007
    4: gpu008
- id: ggpu01-09
  name: gpu009-gpu012
  template_id: hpc-4u-quad-gpu
  u_position: 9
  face: front
  instance:
    1: gpu009
    2: gpu010
    3: gpu011
    4: gpu012
- id: ggpu01-13
  name: gpu013-gpu016
  template_id: hpc-4u-quad-gpu
  u_position: 13
  face: front
  instance:
    1: gpu013
    2: gpu014
    3: gpu015
    4: gpu016
- id: ggpu01-17
  name: gpu017-gpu020
  template_id: hpc-4u-quad-gpu
  u_position: 17
  face: front
  instance:
    1: gpu017
    2: gpu018
    3: gpu019
    4: gpu020
- id: ggpu01-21
  name: gpu021-gpu024
  template_id: hpc-4u-quad-gpu
  u_position: 21
  face: front
  instance:
    1: gpu021
    2: gpu022
    3: gpu023
    4: gpu024
- id: ggpu01-25
  name: gpu025-gpu028
  template_id: hpc-4u-quad-gpu
  u_position: 25
  face: front
  instance:
    1: gpu025
    2: gpu026
    3: gpu027
    4: gpu028
- id: ggpu01-29
  name: gpu029-gpu032
  template_id: hpc-4u-quad-gpu
  u_position: 29
  face: front
  instance:
    1: gpu029
    2: gpu030
    3: gpu031
    4: gpu032
- id: ggpu01-33
  name: gpu033-gpu036
  template_id: hpc-4u-quad-gpu
  u_position: 33
  face: front
  instance:
    1: gpu033
    2: gpu034
    3: gpu035
    4: gpu036
- id: ggpu01-37
  name: gpu037-gpu040
  template_id: hpc-4u-quad-gpu
  u_position: 37
  face: front
  instance:
    1: gpu037
    2: gpu038
    3: gpu039
    4: gpu040
- id: tor-rack-gpu01
  name: tor-rack-gpu01
  template_id: generic-tor-eth-1u
  u_position: 42
  face: front
  instance: tor-rack-gpu01
- id: sw-ib-rack-gpu01
  name: ib-rack-gpu01
  template_id: generic-ib-switch-1u
  u_position: 41
  face: front
  instance: ib-rack-gpu01
