id: rack-tou-c025
name: Compute Rack rack-tou-c025
u_height: 42
template_id: rack-42u-dcw
devices:
- id: cc025-01
  name: compute8641-compute8643
  template_id: hpc-1u-3node
  u_position: 1
  face: front
  instance:
    1: compute8641
    2: compute8642
    3: compute8643
- id: cc025-02
  name: compute8644-compute8646
  template_id: hpc-1u-3node
  u_position: 2
  face: front
  instance:
    1: compute8644
    2: compute8645
    3: compute8646
- id: cc025-03
  name: compute8647-compute8649
  template_id: hpc-1u-3node
  u_position: 3
  face: front
  instance:
    1: compute8647
    2: compute8648
    3: compute8649
- id: cc025-04
  name: compute8650-compute8652
  template_id: hpc-1u-3node
  u_position: 4
  face: front
  instance:
    1: compute8650
    2: compute8651
    3: compute8652
- id: cc025-05
  name: compute8653-compute8655
  template_id: hpc-1u-3node
  u_position: 5
  face: front
  instance:
    1: compute8653
    2: compute8654
    3: compute8655
- id: cc025-06
  name: compute8656-compute8658
  template_id: hpc-1u-3node
  u_position: 6
  face: front
  instance:
    1: compute8656
    2: compute8657
    3: compute8658
- id: cc025-07
  name: compute8659-compute8661
  template_id: hpc-1u-3node
  u_position: 7
  face: front
  instance:
    1: compute8659
    2: compute8660
    3: compute8661
- id: cc025-08
  name: compute8662-compute8664
  template_id: hpc-1u-3node
  u_position: 8
  face: front
  instance:
    1: compute8662
    2: compute8663
    3: compute8664
- id: cc025-09
  name: compute8665-compute8667
  template_id: hpc-1u-3node
  u_position: 9
  face: front
  instance:
    1: compute8665
    2: compute8666
    3: compute8667
- id: cc025-10
  name: compute8668-compute8670
  template_id: hpc-1u-3node
  u_position: 10
  face: front
  instance:
    1: compute8668
    2: compute8669
    3: compute8670
- id: cc025-11
  name: compute8671-compute8673
  template_id: hpc-1u-3node
  u_position: 11
  face: front
  instance:
    1: compute8671
    2: compute8672
    3: compute8673
- id: cc025-12
  name: compute8674-compute8676
  template_id: hpc-1u-3node
  u_position: 12
  face: front
  instance:
    1: compute8674
    2: compute8675
    3: compute8676
- id: cc025-13
  name: compute8677-compute8679
  template_id: hpc-1u-3node
  u_position: 13
  face: front
  instance:
    1: compute8677
    2: compute8678
    3: compute8679
- id: cc025-14
  name: compute8680-compute8682
  template_id: hpc-1u-3node
  u_position: 14
  face: front
  instance:
    1: compute8680
    2: compute8681
    3: compute8682
- id: cc025-15
  name: compute8683-compute8685
  template_id: hpc-1u-3node
  u_position: 15
  face: front
  instance:
    1: compute8683
    2: compute8684
    3: compute8685
- id: cc025-16
  name: compute8686-compute8688
  template_id: hpc-1u-3node
  u_position: 16
  face: front
  instance:
    1: compute8686
    2: compute8687
    3: compute8688
- id: cc025-17
  name: compute8689-compute8691
  template_id: hpc-1u-3node
  u_position: 17
  face: front
  instance:
    1: compute8689
    2: compute8690
    3: compute8691
- id: cc025-18
  name: compute8692-compute8694
  template_id: hpc-1u-3node
  u_position: 18
  face: front
  instance:
    1: compute8692
    2: compute8693
    3: compute8694
- id: cc025-19
  name: compute8695-compute8697
  template_id: hpc-1u-3node
  u_position: 19
  face: front
  instance:
    1: compute8695
    2: compute8696
    3: compute8697
- id: cc025-20
  name: compute8698-compute8700
  template_id: hpc-1u-3node
  u_position: 20
  face: front
  instance:
    1: compute8698
    2: compute8699
    3: compute8700
- id: cc025-21
  name: compute8701-compute8703
  template_id: hpc-1u-3node
  u_position: 21
  face: front
  instance:
    1: compute8701
    2: compute8702
    3: compute8703
- id: cc025-22
  name: compute8704-compute8706
  template_id: hpc-1u-3node
  u_position: 22
  face: front
  instance:
    1: compute8704
    2: compute8705
    3: compute8706
- id: cc025-23
  name: compute8707-compute8709
  template_id: hpc-1u-3node
  u_position: 23
  face: front
  instance:
    1: compute8707
    2: compute8708
    3: compute8709
- id: cc025-24
  name: compute8710-compute8712
  template_id: hpc-1u-3node
  u_position: 24
  face: front
  instance:
    1: compute8710
    2: compute8711
    3: compute8712
- id: cc025-25
  name: compute8713-compute8715
  template_id: hpc-1u-3node
  u_position: 25
  face: front
  instance:
    1: compute8713
    2: compute8714
    3: compute8715
- id: cc025-26
  name: compute8716-compute8718
  template_id: hpc-1u-3node
  u_position: 26
  face: front
  instance:
    1: compute8716
    2: compute8717
    3: compute8718
- id: cc025-27
  name: compute8719-compute8721
  template_id: hpc-1u-3node
  u_position: 27
  face: front
  instance:
    1: compute8719
    2: compute8720
    3: compute8721
- id: cc025-28
  name: compute8722-compute8724
  template_id: hpc-1u-3node
  u_position: 28
  face: front
  instance:
    1: compute8722
    2: compute8723
    3: compute8724
- id: cc025-29
  name: compute8725-compute8727
  template_id: hpc-1u-3node
  u_position: 29
  face: front
  instance:
    1: compute8725
    2: compute8726
    3: compute8727
- id: cc025-30
  name: compute8728-compute8730
  template_id: hpc-1u-3node
  u_position: 30
  face: front
  instance:
    1: compute8728
    2: compute8729
    3: compute8730
- id: cc025-31
  name: compute8731-compute8733
  template_id: hpc-1u-3node
  u_position: 31
  face: front
  instance:
    1: compute8731
    2: compute8732
    3: compute8733
- id: cc025-32
  name: compute8734-compute8736
  template_id: hpc-1u-3node
  u_position: 32
  face: front
  instance:
    1: compute8734
    2: compute8735
    3: compute8736
- id: cc025-33
  name: compute8737-compute8739
  template_id: hpc-1u-3node
  u_position: 33
  face: front
  instance:
    1: compute8737
    2: compute8738
    3: compute8739
- id: cc025-34
  name: compute8740-compute8742
  template_id: hpc-1u-3node
  u_position: 34
  face: front
  instance:
    1: compute8740
    2: compute8741
    3: compute8742
- id: cc025-35
  name: compute8743-compute8745
  template_id: hpc-1u-3node
  u_position: 35
  face: front
  instance:
    1: compute8743
    2: compute8744
    3: compute8745
- id: cc025-36
  name: compute8746-compute8748
  template_id: hpc-1u-3node
  u_position: 36
  face: front
  instance:
    1: compute8746
    2: compute8747
    3: compute8748
- id: cc025-37
  name: compute8749-compute8751
  template_id: hpc-1u-3node
  u_position: 37
  face: front
  instance:
    1: compute8749
    2: compute8750
    3: compute8751
- id: cc025-38
  name: compute8752-compute8754
  template_id: hpc-1u-3node
  u_position: 38
  face: front
  instance:
    1: compute8752
    2: compute8753
    3: compute8754
- id: cc025-39
  name: compute8755-compute8757
  template_id: hpc-1u-3node
  u_position: 39
  face: front
  instance:
    1: compute8755
    2: compute8756
    3: compute8757
- id: cc025-40
  name: compute8758-compute8760
  template_id: hpc-1u-3node
  u_position: 40
  face: front
  instance:
    1: compute8758
    2: compute8759
    3: compute8760
- id: tor-rack-tou-c025
  name: tor-rack-tou-c025
  template_id: generic-tor-eth-1u
  u_position: 42
  face: front
  instance: tor-rack-tou-c025
