id: rack-tou-net
name: Network Rack — site-toulouse
u_height: 42
template_id: rack-42u-air
devices:
- id: sw-core-tou1
  name: core-tou-01
  template_id: generic-core-eth-2u
  u_position: 1
  face: front
  instance: core-tou-01
- id: sw-core-tou2
  name: core-tou-02
  template_id: generic-core-eth-2u
  u_position: 3
  face: front
  instance: core-tou-02
- id: sw-core-tou3
  name: core-tou-03
  template_id: generic-core-eth-2u
  u_position: 5
  face: front
  instance: core-tou-03
- id: sw-ib-l2-tou1
  name: ib-l2-tou-01
  template_id: generic-ib-switch-2u
  u_position: 7
  face: front
  instance: ib-l2-tou-01
- id: sw-ib-l2-tou2
  name: ib-l2-tou-02
  template_id: generic-ib-switch-2u
  u_position: 9
  face: front
  instance: ib-l2-tou-02
- id: sw-ib-l1-tou1
  name: ib-l1-tou-01
  template_id: generic-ib-switch-1u
  u_position: 11
  face: front
  instance: ib-l1-tou-01
- id: sw-ib-l1-tou2
  name: ib-l1-tou-02
  template_id: generic-ib-switch-1u
  u_position: 12
  face: front
  instance: ib-l1-tou-02
- id: sw-ib-l1-tou3
  name: ib-l1-tou-03
  template_id: generic-ib-switch-1u
  u_position: 13
  face: front
  instance: ib-l1-tou-03
- id: sw-ib-l1-tou4
  name: ib-l1-tou-04
  template_id: generic-ib-switch-1u
  u_position: 14
  face: front
  instance: ib-l1-tou-04
- id: sw-mgmt-tou1
  name: mgmt-sw-tou-01
  template_id: generic-mgmt-switch-1u
  u_position: 15
  face: front
  instance: mgmt-sw-tou-01
- id: sw-mgmt-tou2
  name: mgmt-sw-tou-02
  template_id: generic-mgmt-switch-1u
  u_position: 16
  face: front
  instance: mgmt-sw-tou-02
