templates:
- id: eth-switch-tor
  name: Ethernet Mgmt Switch
  type: network
  role: ethernet
  u_height: 1
  layout:
    type: grid
    rows: 1
    cols: 1
    matrix:
    - - 1
  rear_layout:
    type: grid
    rows: 1
    cols: 2
    matrix:
    - - 901
      - 902
  checks:
  - node_up
  - switch_up
  - switch_temp_warn
  - switch_temp_crit
  - switch_power_warn
  - switch_power_crit
  metrics:
  - node_temperature
  - node_power
