id: rack-par-sto
name: Storage Rack — site-paris
u_height: 42
template_id: rack-42u-air
devices:
- id: sto-par01
  name: sto-par-01
  template_id: generic-1u-storage-head
  u_position: 1
  face: front
  instance: sto-par-01
- id: sto-par02
  name: sto-par-02
  template_id: generic-1u-storage-head
  u_position: 2
  face: front
  instance: sto-par-02
- id: sto-par03
  name: sto-par-03
  template_id: generic-1u-storage-head
  u_position: 3
  face: front
  instance: sto-par-03
- id: sto-par04
  name: sto-par-04
  template_id: generic-1u-storage-head
  u_position: 4
  face: front
  instance: sto-par-04
- id: sto-par05
  name: sto-par-05
  template_id: generic-1u-storage-head
  u_position: 5
  face: front
  instance: sto-par-05
- id: sto-par06
  name: sto-par-06
  template_id: generic-1u-storage-head
  u_position: 6
  face: front
  instance: sto-par-06
- id: sto-par07
  name: sto-par-07
  template_id: generic-1u-storage-head
  u_position: 7
  face: front
  instance: sto-par-07
- id: sto-par08
  name: sto-par-08
  template_id: generic-1u-storage-head
  u_position: 8
  face: front
  instance: sto-par-08
- id: sto-par09
  name: sto-par-09
  template_id: generic-1u-storage-head
  u_position: 9
  face: front
  instance: sto-par-09
- id: sto-par10
  name: sto-par-10
  template_id: generic-1u-storage-head
  u_position: 10
  face: front
  instance: sto-par-10
- id: sto-par11
  name: sto-par-11
  template_id: generic-1u-storage-head
  u_position: 11
  face: front
  instance: sto-par-11
- id: sto-par12
  name: sto-par-12
  template_id: generic-1u-storage-head
  u_position: 12
  face: front
  instance: sto-par-12
- id: sto-par13
  name: sto-par-13
  template_id: generic-1u-storage-head
  u_position: 13
  face: front
  instance: sto-par-13
- id: sto-par14
  name: sto-par-14
  template_id: generic-1u-storage-head
  u_position: 14
  face: front
  instance: sto-par-14
- id: sto-par15
  name: sto-par-15
  template_id: generic-1u-storage-head
  u_position: 15
  face: front
  instance: sto-par-15
- id: sto-par16
  name: sto-par-16
  template_id: generic-1u-storage-head
  u_position: 16
  face: front
  instance: sto-par-16
- id: sto-par17
  name: sto-par-17
  template_id: generic-1u-storage-head
  u_position: 17
  face: front
  instance: sto-par-17
- id: sw-eth-sto-par
  name: tor-sto-par
  template_id: generic-tor-eth-1u
  u_position: 42
  face: front
  instance: tor-sto-par
- id: sw-ib-sto-par
  name: ib-sto-par
  template_id: generic-ib-switch-1u
  u_position: 41
  face: front
  instance: ib-sto-par
