id: rack-tls-c08
name: Compute Rack TLS C08
u_height: 42
template_id: bull-xh3000
devices:
- id: hpc-tls-c08-01
  name: tls-compute0841-tls-compute0843
  template_id: bs-xh3150-tino-1u-3n
  u_position: 1
  face: front
  instance:
    1: tls-compute0841
    2: tls-compute0842
    3: tls-compute0843
- id: hpc-tls-c08-02
  name: tls-compute0844-tls-compute0846
  template_id: bs-xh3150-tino-1u-3n
  u_position: 2
  face: front
  instance:
    1: tls-compute0844
    2: tls-compute0845
    3: tls-compute0846
- id: hpc-tls-c08-03
  name: tls-compute0847-tls-compute0849
  template_id: bs-xh3150-tino-1u-3n
  u_position: 3
  face: front
  instance:
    1: tls-compute0847
    2: tls-compute0848
    3: tls-compute0849
- id: hpc-tls-c08-04
  name: tls-compute0850-tls-compute0852
  template_id: bs-xh3150-tino-1u-3n
  u_position: 4
  face: front
  instance:
    1: tls-compute0850
    2: tls-compute0851
    3: tls-compute0852
- id: hpc-tls-c08-05
  name: tls-compute0853-tls-compute0855
  template_id: bs-xh3150-tino-1u-3n
  u_position: 5
  face: front
  instance:
    1: tls-compute0853
    2: tls-compute0854
    3: tls-compute0855
- id: hpc-tls-c08-06
  name: tls-compute0856-tls-compute0858
  template_id: bs-xh3150-tino-1u-3n
  u_position: 6
  face: front
  instance:
    1: tls-compute0856
    2: tls-compute0857
    3: tls-compute0858
- id: hpc-tls-c08-07
  name: tls-compute0859-tls-compute0861
  template_id: bs-xh3150-tino-1u-3n
  u_position: 7
  face: front
  instance:
    1: tls-compute0859
    2: tls-compute0860
    3: tls-compute0861
- id: hpc-tls-c08-08
  name: tls-compute0862-tls-compute0864
  template_id: bs-xh3150-tino-1u-3n
  u_position: 8
  face: front
  instance:
    1: tls-compute0862
    2: tls-compute0863
    3: tls-compute0864
- id: hpc-tls-c08-09
  name: tls-compute0865-tls-compute0867
  template_id: bs-xh3150-tino-1u-3n
  u_position: 9
  face: front
  instance:
    1: tls-compute0865
    2: tls-compute0866
    3: tls-compute0867
- id: hpc-tls-c08-10
  name: tls-compute0868-tls-compute0870
  template_id: bs-xh3150-tino-1u-3n
  u_position: 10
  face: front
  instance:
    1: tls-compute0868
    2: tls-compute0869
    3: tls-compute0870
- id: hpc-tls-c08-11
  name: tls-compute0871-tls-compute0873
  template_id: bs-xh3150-tino-1u-3n
  u_position: 11
  face: front
  instance:
    1: tls-compute0871
    2: tls-compute0872
    3: tls-compute0873
- id: hpc-tls-c08-12
  name: tls-compute0874-tls-compute0876
  template_id: bs-xh3150-tino-1u-3n
  u_position: 12
  face: front
  instance:
    1: tls-compute0874
    2: tls-compute0875
    3: tls-compute0876
- id: hpc-tls-c08-13
  name: tls-compute0877-tls-compute0879
  template_id: bs-xh3150-tino-1u-3n
  u_position: 13
  face: front
  instance:
    1: tls-compute0877
    2: tls-compute0878
    3: tls-compute0879
- id: hpc-tls-c08-14
  name: tls-compute0880-tls-compute0882
  template_id: bs-xh3150-tino-1u-3n
  u_position: 14
  face: front
  instance:
    1: tls-compute0880
    2: tls-compute0881
    3: tls-compute0882
- id: hpc-tls-c08-15
  name: tls-compute0883-tls-compute0885
  template_id: bs-xh3150-tino-1u-3n
  u_position: 15
  face: front
  instance:
    1: tls-compute0883
    2: tls-compute0884
    3: tls-compute0885
- id: hpc-tls-c08-16
  name: tls-compute0886-tls-compute0888
  template_id: bs-xh3150-tino-1u-3n
  u_position: 16
  face: front
  instance:
    1: tls-compute0886
    2: tls-compute0887
    3: tls-compute0888
- id: hpc-tls-c08-17
  name: tls-compute0889-tls-compute0891
  template_id: bs-xh3150-tino-1u-3n
  u_position: 17
  face: front
  instance:
    1: tls-compute0889
    2: tls-compute0890
    3: tls-compute0891
- id: hpc-tls-c08-18
  name: tls-compute0892-tls-compute0894
  template_id: bs-xh3150-tino-1u-3n
  u_position: 18
  face: front
  instance:
    1: tls-compute0892
    2: tls-compute0893
    3: tls-compute0894
- id: hpc-tls-c08-19
  name: tls-compute0895-tls-compute0897
  template_id: bs-xh3150-tino-1u-3n
  u_position: 19
  face: front
  instance:
    1: tls-compute0895
    2: tls-compute0896
    3: tls-compute0897
- id: hpc-tls-c08-20
  name: tls-compute0898-tls-compute0900
  template_id: bs-xh3150-tino-1u-3n
  u_position: 20
  face: front
  instance:
    1: tls-compute0898
    2: tls-compute0899
    3: tls-compute0900
- id: hpc-tls-c08-21
  name: tls-compute0901-tls-compute0903
  template_id: bs-xh3150-tino-1u-3n
  u_position: 21
  face: front
  instance:
    1: tls-compute0901
    2: tls-compute0902
    3: tls-compute0903
- id: hpc-tls-c08-22
  name: tls-compute0904-tls-compute0906
  template_id: bs-xh3150-tino-1u-3n
  u_position: 22
  face: front
  instance:
    1: tls-compute0904
    2: tls-compute0905
    3: tls-compute0906
- id: hpc-tls-c08-23
  name: tls-compute0907-tls-compute0909
  template_id: bs-xh3150-tino-1u-3n
  u_position: 23
  face: front
  instance:
    1: tls-compute0907
    2: tls-compute0908
    3: tls-compute0909
- id: hpc-tls-c08-24
  name: tls-compute0910-tls-compute0912
  template_id: bs-xh3150-tino-1u-3n
  u_position: 24
  face: front
  instance:
    1: tls-compute0910
    2: tls-compute0911
    3: tls-compute0912
- id: hpc-tls-c08-25
  name: tls-compute0913-tls-compute0915
  template_id: bs-xh3150-tino-1u-3n
  u_position: 25
  face: front
  instance:
    1: tls-compute0913
    2: tls-compute0914
    3: tls-compute0915
- id: hpc-tls-c08-26
  name: tls-compute0916-tls-compute0918
  template_id: bs-xh3150-tino-1u-3n
  u_position: 26
  face: front
  instance:
    1: tls-compute0916
    2: tls-compute0917
    3: tls-compute0918
- id: hpc-tls-c08-27
  name: tls-compute0919-tls-compute0921
  template_id: bs-xh3150-tino-1u-3n
  u_position: 27
  face: front
  instance:
    1: tls-compute0919
    2: tls-compute0920
    3: tls-compute0921
- id: hpc-tls-c08-28
  name: tls-compute0922-tls-compute0924
  template_id: bs-xh3150-tino-1u-3n
  u_position: 28
  face: front
  instance:
    1: tls-compute0922
    2: tls-compute0923
    3: tls-compute0924
- id: hpc-tls-c08-29
  name: tls-compute0925-tls-compute0927
  template_id: bs-xh3150-tino-1u-3n
  u_position: 29
  face: front
  instance:
    1: tls-compute0925
    2: tls-compute0926
    3: tls-compute0927
- id: hpc-tls-c08-30
  name: tls-compute0928-tls-compute0930
  template_id: bs-xh3150-tino-1u-3n
  u_position: 30
  face: front
  instance:
    1: tls-compute0928
    2: tls-compute0929
    3: tls-compute0930
- id: hpc-tls-c08-31
  name: tls-compute0931-tls-compute0933
  template_id: bs-xh3150-tino-1u-3n
  u_position: 31
  face: front
  instance:
    1: tls-compute0931
    2: tls-compute0932
    3: tls-compute0933
- id: hpc-tls-c08-32
  name: tls-compute0934-tls-compute0936
  template_id: bs-xh3150-tino-1u-3n
  u_position: 32
  face: front
  instance:
    1: tls-compute0934
    2: tls-compute0935
    3: tls-compute0936
- id: hpc-tls-c08-33
  name: tls-compute0937-tls-compute0939
  template_id: bs-xh3150-tino-1u-3n
  u_position: 33
  face: front
  instance:
    1: tls-compute0937
    2: tls-compute0938
    3: tls-compute0939
- id: hpc-tls-c08-34
  name: tls-compute0940-tls-compute0942
  template_id: bs-xh3150-tino-1u-3n
  u_position: 34
  face: front
  instance:
    1: tls-compute0940
    2: tls-compute0941
    3: tls-compute0942
- id: hpc-tls-c08-35
  name: tls-compute0943-tls-compute0945
  template_id: bs-xh3150-tino-1u-3n
  u_position: 35
  face: front
  instance:
    1: tls-compute0943
    2: tls-compute0944
    3: tls-compute0945
- id: hpc-tls-c08-36
  name: tls-compute0946-tls-compute0948
  template_id: bs-xh3150-tino-1u-3n
  u_position: 36
  face: front
  instance:
    1: tls-compute0946
    2: tls-compute0947
    3: tls-compute0948
- id: hpc-tls-c08-37
  name: tls-compute0949-tls-compute0951
  template_id: bs-xh3150-tino-1u-3n
  u_position: 37
  face: front
  instance:
    1: tls-compute0949
    2: tls-compute0950
    3: tls-compute0951
- id: sw-ib-tls-c08
  name: sw-ib-tls-c08
  template_id: bs-xh35mq-ib-1u
  u_position: 38
  face: front
  instance: sw-ib-tls-c08
