id: rack-par-svc
name: Services Rack — site-paris
u_height: 42
template_id: rack-42u-air
devices:
- id: login-par01
  name: login-par-01
  template_id: generic-1u-login
  u_position: 1
  face: front
  instance: login-par-01
- id: login-par02
  name: login-par-02
  template_id: generic-1u-login
  u_position: 2
  face: front
  instance: login-par-02
- id: login-par03
  name: login-par-03
  template_id: generic-1u-login
  u_position: 3
  face: front
  instance: login-par-03
- id: login-par04
  name: login-par-04
  template_id: generic-1u-login
  u_position: 4
  face: front
  instance: login-par-04
- id: login-par05
  name: login-par-05
  template_id: generic-1u-login
  u_position: 5
  face: front
  instance: login-par-05
- id: login-par06
  name: login-par-06
  template_id: generic-1u-login
  u_position: 6
  face: front
  instance: login-par-06
- id: login-par07
  name: login-par-07
  template_id: generic-1u-login
  u_position: 7
  face: front
  instance: login-par-07
- id: login-par08
  name: login-par-08
  template_id: generic-1u-login
  u_position: 8
  face: front
  instance: login-par-08
- id: visu-par01
  name: visu-par-01
  template_id: generic-2u-visu
  u_position: 9
  face: front
  instance:
    1: visu-par-01
- id: visu-par02
  name: visu-par-02
  template_id: generic-2u-visu
  u_position: 11
  face: front
  instance:
    1: visu-par-02
- id: visu-par03
  name: visu-par-03
  template_id: generic-2u-visu
  u_position: 13
  face: front
  instance:
    1: visu-par-03
- id: visu-par04
  name: visu-par-04
  template_id: generic-2u-visu
  u_position: 15
  face: front
  instance:
    1: visu-par-04
- id: mgmt-par01
  name: mgmt-par-01
  template_id: generic-1u-mgmt
  u_position: 17
  face: front
  instance: mgmt-par-01
- id: mgmt-par02
  name: mgmt-par-02
  template_id: generic-1u-mgmt
  u_position: 18
  face: front
  instance: mgmt-par-02
- id: mgmt-par03
  name: mgmt-par-03
  template_id: generic-1u-mgmt
  u_position: 19
  face: front
  instance: mgmt-par-03
- id: mgmt-par04
  name: mgmt-par-04
  template_id: generic-1u-mgmt
  u_position: 20
  face: front
  instance: mgmt-par-04
- id: mgmt-par05
  name: mgmt-par-05
  template_id: generic-1u-mgmt
  u_position: 21
  face: front
  instance: mgmt-par-05
- id: mgmt-par06
  name: mgmt-par-06
  template_id: generic-1u-mgmt
  u_position: 22
  face: front
  instance: mgmt-par-06
- id: sw-eth-svc-par
  name: tor-svc-par
  template_id: generic-tor-eth-1u
  u_position: 42
  face: front
  instance: tor-svc-par
- id: sw-ib-svc-par
  name: ib-svc-par
  template_id: generic-ib-switch-1u
  u_position: 41
  face: front
  instance: ib-svc-par
