checks:
  - id: ipmi_fan_speed_state
    name: IPMI fan speed state
    scope: node
    kind: ipmi
    expr: ipmi_fan_speed_state{instance=~"$instances"}
    output: numeric
    rules:
      - op: "=="
        value: 1
        severity: WARN
      - op: "=="
        value: 2
        severity: CRIT

  - id: ipmi_power_state
    name: IPMI power state
    scope: node
    kind: ipmi
    expr: ipmi_power_state{instance=~"$instances"}
    output: numeric
    rules:
      - op: "=="
        value: 1
        severity: WARN
      - op: "=="
        value: 2
        severity: CRIT

  - id: ipmi_sensor_state
    name: IPMI sensor state
    scope: node
    kind: ipmi
    expr: ipmi_sensor_state{name!~"Low Security Jmp|Phy Presence Jmp|Dongle Cable",instance=~"$instances"}
    output: numeric
    rules:
      - op: "=="
        value: 1
        severity: WARN
      - op: "=="
        value: 2
        severity: CRIT

  - id: ipmi_temperature_state
    name: IPMI temperature state
    scope: node
    kind: ipmi
    expr: ipmi_temperature_state{instance=~"$instances"}
    output: numeric
    rules:
      - op: "=="
        value: 1
        severity: WARN
      - op: "=="
        value: 2
        severity: CRIT

  - id: ipmi_up
    name: IPMI exporter up
    scope: node
    kind: ipmi
    expr: ipmi_up{instance=~"$instances"}
    output: bool
    rules:
      - op: "=="
        value: 0
        severity: CRIT

  - id: ipmi_voltage_state
    name: IPMI voltage state
    scope: node
    kind: ipmi
    expr: ipmi_voltage_state{instance=~"$instances"}
    output: numeric
    rules:
      - op: "=="
        value: 1
        severity: WARN
      - op: "=="
        value: 2
        severity: CRIT
