id: rack-tls-sto02
name: Storage Rack TLS STO02
u_height: 42
template_id: standard-42u-air
devices:
- id: sto-tls-head02
  name: sto-tls-head02
  template_id: generic-1u-storage-head
  u_position: 1
  face: front
  instance: sto-tls-head02
- id: sto-tls-jbod03
  name: sto-tls-jbod03
  template_id: generic-2u-jbod
  u_position: 2
  face: front
  instance: sto-tls-jbod03
- id: sto-tls-jbod04
  name: sto-tls-jbod04
  template_id: generic-2u-jbod
  u_position: 4
  face: front
  instance: sto-tls-jbod04
- id: sw-eth-tls-sto02
  name: sw-eth-tls-sto02
  template_id: eth-switch-tor
  u_position: 6
  face: front
  instance: sw-eth-tls-sto02
