templates:
- id: storage-4u-60disk
  name: High Density Drawer 4U (60 LFF)
  type: storage
  storage_type: eseries
  role: stockage
  u_height: 4
  disk_layout:
    type: grid
    rows: 5
    cols: 12
    matrix:
    - [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    - [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
    - [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]
    - [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]
    - [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]
  checks:
  - node_up
  - node_recent_reboot
  - eseries_exporter_collect_error
  - eseries_storage_system_status
  - eseries_drive_status
  - eseries_battery_status
  - eseries_fan_status
  - eseries_power_supply_status
  - eseries_cache_memory_dimm_status
  - eseries_thermal_sensor_status
  metrics:
  - node_up
  - node_temperature
  - node_power
  - eseries_exporter_collect_error
  - eseries_storage_system_status
  - eseries_drive_status
  - eseries_battery_status
  - eseries_fan_status
  - eseries_power_supply_status
