templates:
- id: generic-1u-storage-head
  name: Storage Head Node 1U
  type: server
  u_height: 1
  role: storage
  layout:
    type: grid
    rows: 1
    cols: 1
    matrix:
    - - 1
  checks:
  - node_up
  - ipmi_temp_warn
  metrics:
  - node_power
- id: generic-2u-jbod
  name: JBOD Storage 2U
  type: storage
  u_height: 2
  checks: []
  metrics: []
