metrics:
  - id: pdu_active_power
    name: PDU Active Power
    description: Total active power on PDU
    metric: pdu_total_load_watts{rack_id="$rack_id"}
    display:
      unit: W
      chart_type: line
      color: '#8b5cf6'
    category: power
    tags:
      - pdu
      - power
