metrics:
  - id: pdu_current
    name: PDU Current
    description: Current per PDU outlet
    metric: raritan_pdu_current_ampere{rack_id="$rack_id"}
    display:
      unit: A
      chart_type: line
      color: '#06b6d4'
    category: power
    tags:
      - pdu
      - power
