id: aisle-compute-2
name: Aisle Compute 2
room_id: room-compute-a
racks:
- id: rack-par-c003
- id: rack-par-c004
- id: rack-par-c005
- id: rack-par-c006
- id: rack-par-c007
- id: rack-par-c008
- id: rack-par-c009
- id: rack-par-c010
- id: rack-par-c011
- id: rack-par-c012
