id: r02-04
name: Rack Storage 04
template_id: standard-42u-air
aisle_id: aisle-02
devices:
- id: r02-04-ib
  name: IB Switch
  template_id: ib-switch-l1
  u_position: 42
- id: r02-04-esw
  name: Ethernet Switch
  template_id: eth-switch-tor
  u_position: 40
- id: r02-04-da01
  name: Disk Array 01
  template_id: storage-4u-60disk
  u_position: 1
  instance: hdd-r02-04-d1[01-60]
- id: r02-04-da02
  name: Disk Array 02
  template_id: storage-4u-60disk
  u_position: 5
  instance: hdd-r02-04-d2[01-60]
- id: r02-04-da03
  name: Disk Array 03
  template_id: storage-4u-60disk
  u_position: 9
  instance: hdd-r02-04-d3[01-60]
- id: r02-04-da04
  name: Disk Array 04
  template_id: storage-4u-60disk
  u_position: 13
  instance: hdd-r02-04-d4[01-60]
- id: r02-04-da05
  name: Disk Array 05
  template_id: storage-4u-60disk
  u_position: 17
  instance: hdd-r02-04-d5[01-60]
- id: r02-04-da06
  name: Disk Array 06
  template_id: storage-4u-60disk
  u_position: 21
  instance: hdd-r02-04-d6[01-60]
- id: r02-04-s01
  name: Service 01
  template_id: bs-x430-service-2u
  u_position: 25
  instance:
    1: service007
- id: r02-04-s02
  name: Service 02
  template_id: bs-x430-service-2u
  u_position: 27
  instance:
    1: service008
