#!/usr/bin/env python3
"""
Generate STATUS.md from CI environment variables.
Called by .github/workflows/ci.yml after all jobs complete.

Can also be run locally (values default to "pending"):
    python3 scripts/gen_status.py
"""

import datetime
import os


def icon(status: str) -> str:
    # Handles both legacy "passing/failing" and GitHub Actions "success/failure" outcomes
    norm = {"success": "passing", "failure": "failing", "skipped": "warning"}.get(status, status)
    return {"passing": "\u2705", "warning": "\u26a0\ufe0f", "failing": "\u274c"}.get(
        norm, "\u2b1c"
    )


now = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
sha = (os.environ.get("COMMIT_SHA") or "")[:7]
repo = os.environ.get("REPO", "")
srv = os.environ.get("SERVER_URL", "https://github.com")
rid = os.environ.get("RUN_ID", "")
run_url = f"{srv}/{repo}/actions/runs/{rid}" if rid else "#"
commit_url = f"{srv}/{repo}/commit/{os.environ.get('COMMIT_SHA', '')}" if repo else "#"

t_ok = os.environ.get("TESTS_PASSED") or "?"
t_ko = os.environ.get("TESTS_FAILED") or "0"
cov = os.environ.get("COVERAGE") or "?"

be_lint = os.environ.get("BE_LINT") or "unknown"
be_mypy = os.environ.get("BE_MYPY") or "unknown"
be_audit = os.environ.get("BE_AUDIT") or "unknown"
be_av = os.environ.get("BE_AUDIT_VULNS") or "0"

fe_lint = os.environ.get("FE_LINT") or "unknown"
fe_build = os.environ.get("FE_BUILD") or "unknown"
fe_audit = os.environ.get("FE_AUDIT") or "unknown"
fe_av = os.environ.get("FE_AUDIT_VULNS") or "0"

tests_ok = t_ko == "0"
tests_icon = "\u2705" if tests_ok else "\u274c"

be_audit_detail = (
    f"pip-audit \u00b7 {be_av} vulns" if be_audit == "warning" else "pip-audit \u00b7 clean"
)
fe_audit_detail = (
    f"npm audit \u00b7 {fe_av} high/critical" if fe_audit == "warning" else "npm audit \u00b7 clean"
)

sha_link = f"[{sha}]({commit_url})" if sha else "?"

run_link = f" · [View run]({run_url})" if rid else ""

md = f"""\
# Rackscope \u2014 Status

> Updated: {now} \u00b7 Commit: {sha_link}{run_link}

## Summary

| Check | Status | Detail |
|---|---|---|
| \U0001f9ea **Tests** | {tests_icon} {t_ok} passed | {t_ko} failed \u00b7 {cov}% coverage |
| \U0001f50d **Python lint** | {icon(be_lint)} {be_lint} | ruff check + ruff format |
| \U0001f4d0 **Python types** | {icon(be_mypy)} {be_mypy} | mypy |
| \U0001f3a8 **Frontend lint** | {icon(fe_lint)} {fe_lint} | eslint \u00b7 prettier \u00b7 stylelint |
| \U0001f4e6 **TypeScript** | {icon(fe_build)} {fe_build} | tsc -b |
| \U0001f512 **Python security** | {icon(be_audit)} {be_audit} | {be_audit_detail} |
| \U0001f512 **npm security** | {icon(fe_audit)} {fe_audit} | {fe_audit_detail} |

*Generated by [ci.yml](.github/workflows/ci.yml) \u2014 do not edit manually.*
"""

import json
import pathlib

root = pathlib.Path(os.path.dirname(os.path.dirname(__file__)))

out_path = root / "STATUS.md"
with open(out_path, "w", encoding="utf-8") as f:
    f.write(md)
print(f"STATUS.md written to {out_path}")

# ── Dynamic badges for README shields.io endpoint ─────────────────────────────
badges_dir = root / "badges"
badges_dir.mkdir(exist_ok=True)

tests_color = "brightgreen" if tests_ok else "red"
tests_badge = {
    "schemaVersion": 1,
    "label": "tests",
    "message": f"{t_ok} passing",
    "color": tests_color,
}

cov_num = int(cov) if str(cov).isdigit() else 0
cov_color = "brightgreen" if cov_num >= 90 else "yellow" if cov_num >= 75 else "red"
cov_badge = {
    "schemaVersion": 1,
    "label": "coverage",
    "message": f"{cov}%",
    "color": cov_color,
}

(badges_dir / "tests.json").write_text(json.dumps(tests_badge))
(badges_dir / "coverage.json").write_text(json.dumps(cov_badge))
print(f"badges/ written to {badges_dir}")
