id: rack-sto01
name: Storage Rack STO01
u_height: 42
template_id: rack-42u-air
devices:
- id: sto-h01
  name: storage-head-01
  template_id: generic-1u-storage-head
  u_position: 1
  face: front
  instance: storage-head-01
- id: sto-h02
  name: storage-head-02
  template_id: generic-1u-storage-head
  u_position: 2
  face: front
  instance: storage-head-02
- id: sto-h03
  name: storage-head-03
  template_id: generic-1u-storage-head
  u_position: 3
  face: front
  instance: storage-head-03
- id: sto-h04
  name: storage-head-04
  template_id: generic-1u-storage-head
  u_position: 4
  face: front
  instance: storage-head-04
- id: sto-h05
  name: storage-head-05
  template_id: generic-1u-storage-head
  u_position: 5
  face: front
  instance: storage-head-05
- id: sto-h06
  name: storage-head-06
  template_id: generic-1u-storage-head
  u_position: 6
  face: front
  instance: storage-head-06
- id: sto-h07
  name: storage-head-07
  template_id: generic-1u-storage-head
  u_position: 7
  face: front
  instance: storage-head-07
- id: sto-h08
  name: storage-head-08
  template_id: generic-1u-storage-head
  u_position: 8
  face: front
  instance: storage-head-08
- id: sto-h09
  name: storage-head-09
  template_id: generic-1u-storage-head
  u_position: 9
  face: front
  instance: storage-head-09
- id: sto-h10
  name: storage-head-10
  template_id: generic-1u-storage-head
  u_position: 10
  face: front
  instance: storage-head-10
- id: sto-h11
  name: storage-head-11
  template_id: generic-1u-storage-head
  u_position: 11
  face: front
  instance: storage-head-11
- id: sto-h12
  name: storage-head-12
  template_id: generic-1u-storage-head
  u_position: 12
  face: front
  instance: storage-head-12
- id: sto-h13
  name: storage-head-13
  template_id: generic-1u-storage-head
  u_position: 13
  face: front
  instance: storage-head-13
- id: sto-h14
  name: storage-head-14
  template_id: generic-1u-storage-head
  u_position: 14
  face: front
  instance: storage-head-14
- id: sto-h15
  name: storage-head-15
  template_id: generic-1u-storage-head
  u_position: 15
  face: front
  instance: storage-head-15
- id: sw-eth-rack-sto01
  name: tor-rack-sto01
  template_id: generic-tor-eth-1u
  u_position: 42
  face: front
  instance: tor-rack-sto01
- id: sw-ib-rack-sto01
  name: ib-rack-sto01
  template_id: generic-ib-switch-1u
  u_position: 41
  face: front
  instance: ib-rack-sto01
