id: rack-sto02
name: Storage Rack STO02
u_height: 42
template_id: rack-42u-air
devices:
- id: sto-h16
  name: storage-head-16
  template_id: generic-1u-storage-head
  u_position: 1
  face: front
  instance: storage-head-16
- id: sto-h17
  name: storage-head-17
  template_id: generic-1u-storage-head
  u_position: 2
  face: front
  instance: storage-head-17
- id: sto-h18
  name: storage-head-18
  template_id: generic-1u-storage-head
  u_position: 3
  face: front
  instance: storage-head-18
- id: sto-h19
  name: storage-head-19
  template_id: generic-1u-storage-head
  u_position: 4
  face: front
  instance: storage-head-19
- id: sto-h20
  name: storage-head-20
  template_id: generic-1u-storage-head
  u_position: 5
  face: front
  instance: storage-head-20
- id: sto-h21
  name: storage-head-21
  template_id: generic-1u-storage-head
  u_position: 6
  face: front
  instance: storage-head-21
- id: sto-h22
  name: storage-head-22
  template_id: generic-1u-storage-head
  u_position: 7
  face: front
  instance: storage-head-22
- id: sto-h23
  name: storage-head-23
  template_id: generic-1u-storage-head
  u_position: 8
  face: front
  instance: storage-head-23
- id: sto-h24
  name: storage-head-24
  template_id: generic-1u-storage-head
  u_position: 9
  face: front
  instance: storage-head-24
- id: sto-h25
  name: storage-head-25
  template_id: generic-1u-storage-head
  u_position: 10
  face: front
  instance: storage-head-25
- id: sto-h26
  name: storage-head-26
  template_id: generic-1u-storage-head
  u_position: 11
  face: front
  instance: storage-head-26
- id: sto-h27
  name: storage-head-27
  template_id: generic-1u-storage-head
  u_position: 12
  face: front
  instance: storage-head-27
- id: sto-h28
  name: storage-head-28
  template_id: generic-1u-storage-head
  u_position: 13
  face: front
  instance: storage-head-28
- id: sto-h29
  name: storage-head-29
  template_id: generic-1u-storage-head
  u_position: 14
  face: front
  instance: storage-head-29
- id: sto-h30
  name: storage-head-30
  template_id: generic-1u-storage-head
  u_position: 15
  face: front
  instance: storage-head-30
- id: sw-eth-rack-sto02
  name: tor-rack-sto02
  template_id: generic-tor-eth-1u
  u_position: 42
  face: front
  instance: tor-rack-sto02
- id: sw-ib-rack-sto02
  name: ib-rack-sto02
  template_id: generic-ib-switch-1u
  u_position: 41
  face: front
  instance: ib-rack-sto02
