id: aisle-compute-3
name: Aisle Compute 3
room_id: room-compute-a
racks:
- id: rack-tou-c023
- id: rack-tou-c024
- id: rack-tou-c025
- id: rack-tou-c026
- id: rack-tou-c027
- id: rack-tou-c028
- id: rack-tou-c029
- id: rack-tou-c030
- id: rack-tou-c031
- id: rack-tou-c032
