id: r03-02
name: Rack Visu
template_id: standard-42u-air
aisle_id: aisle-03
u_height: 42
devices:
- id: r03-02-ib
  name: IB Switch
  template_id: ib-switch-l1
  u_position: 42
- id: r03-02-esw
  name: Ethernet Switch
  template_id: eth-switch-tor
  u_position: 40
- id: r03-02-v01
  name: Visu 01
  template_id: bs-x450-visu-4u
  u_position: 1
  instance:
    1: visu0
- id: r03-02-v02
  name: Visu 02
  template_id: bs-x450-visu-4u
  u_position: 5
  instance:
    1: visu1
- id: r03-02-v03
  name: Visu 03
  template_id: bs-x450-visu-4u
  u_position: 9
  instance:
    1: visu2
- id: r03-02-v04
  name: Visu 04
  template_id: bs-x450-visu-4u
  u_position: 13
  instance:
    1: visu3
- id: r03-02-v05
  name: Visu 05
  template_id: bs-x450-visu-4u
  u_position: 17
  instance:
    1: visu4
- id: r03-02-v06
  name: Visu 06
  template_id: bs-x450-visu-4u
  u_position: 21
  instance:
    1: visu5
