id: aisle-compute-3
name: Aisle Compute 3
room_id: room-compute-a
racks:
- id: rack-par-c006
- id: rack-par-c007
- id: rack-par-c008
- id: rack-par-c009
- id: rack-par-c010
- id: rack-par-c011
- id: rack-par-c012
- id: rack-par-c013
- id: rack-par-c014
- id: rack-par-c015
